# This script is for decoding decoder raw data collected in file devices.json
# which is generated by ble.py script. 

import sys
import json
import time
import os.path

def decode():
    filename = "devices.json"

    if os.path.exists(filename):
        with open(filename, 'r') as file:
            data = json.load(file)

        for device in data:
            raw_data = device.get("raw data", "")
            if raw_data.startswith("b'") and raw_data.endswith("'"):
                devicename_start = raw_data.find("\\x", 2)
                devicename_end = raw_data.find("\\x", 2) + 5
                devicename = raw_data[devicename_start:devicename_end]
                device["decoded"] = devicename

        with open(filename, 'w') as file:
            json.dump(data, file, indent=2)
    else:
        print("no file called devices.json in this directory")
    

def main(args):
    print("Bluetooth low energy: beginning decoding")

    decode()
    print("saved decoded")

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))